# Generated by Django 3.1.5 on 2021-10-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.FloatField(max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
