# Generated by Django 3.1.5 on 2021-10-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20211016_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeads',
            name='ads_description',
        ),
        migrations.RemoveField(
            model_name='placeads',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placeads',
            name='week_days',
        ),
        migrations.AddField(
            model_name='placeads',
            name='place_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Título do anúncio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeads',
            name='capacity',
            field=models.PositiveSmallIntegerField(verbose_name='Capacidade'),
        ),
    ]
