# Generated by Django 3.1.5 on 2021-10-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211021_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeads',
            name='local_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Casas'), (2, 'Chácaras'), (3, 'Embarcações'), (4, 'Passeios')], verbose_name='Tipo de Local'),
        ),
    ]
