# Generated by Django 3.1.5 on 2021-10-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20211026_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.PositiveSmallIntegerField(choices=[(1, 'daily'), (2, 'package')], verbose_name='Tipo de plano')),
                ('name', models.CharField(max_length=45, verbose_name='Nome')),
                ('price', models.IntegerField(verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('place_ads', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.placeads', verbose_name='Anúncio de local')),
                ('week_days', models.ManyToManyField(to='places.Days', verbose_name='Dias da semana')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
    ]
