# Generated by Django 3.1.5 on 2021-11-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='WeekDay',
        ),
    ]
