# Generated by Django 3.1.5 on 2021-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211128_1124'),
        ('places', '0006_auto_20211104_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AlterField(
            model_name='placeads',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'closed')], default=1, verbose_name='Status'),
        ),
    ]
