# Generated by Django 3.1.5 on 2022-02-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20211216_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cep',
            field=models.CharField(default=12345678, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
