# Generated by Django 3.1.5 on 2023-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20230412_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
