# Generated by Django 3.1.5 on 2021-10-12 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Título do evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do evento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'accepted'), (3, 'refused'), (4, 'canceled')], default=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('dates_selected', models.ManyToManyField(to='places.Date')),
                ('place_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placeads', verbose_name='Anúncio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('event_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventorder', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Histórico de Evento',
                'verbose_name_plural': 'Históricos de Eventos',
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=255, verbose_name='Justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('event_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventorder', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Cancelamento',
                'verbose_name_plural': 'Cancelamentos',
            },
        ),
    ]
