# Generated by Django 3.1.5 on 2021-11-28 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='plan_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'daily'), (2, 'package')], default=1, verbose_name='Tipo de plano'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='eventorder',
            name='dates_selected',
        ),
        migrations.AddField(
            model_name='eventorder',
            name='dates_selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(verbose_name='Data de criação'), default=['2021-05-13T21:10:03.346280Z'], size=None),
            preserve_default=False,
        ),
    ]
