# Generated by Django 3.1.5 on 2022-01-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome do pacote de crédito')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário')),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montante de créditos')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'activated'), (2, 'deactivated')], default=1, verbose_name='Situação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data da criação')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Data da última modificação')),
            ],
            options={
                'verbose_name': 'Pacote de crédito',
                'verbose_name_plural': 'Pacotes de crédito',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'money'), (2, 'credit'), (3, 'debit'), (4, 'pix')], verbose_name='Método')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
            },
        ),
    ]
