# Generated by Django 3.1.5 on 2022-01-24 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20211216_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_creditpack_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Bandeira')),
                ('last_digits', models.CharField(max_length=4, verbose_name='4 Últimos dígitos')),
                ('holder_name', models.CharField(max_length=60, verbose_name='Nome do Titular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.address', verbose_name='Endereço de cobrança')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='CreditOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'completed'), (3, 'canceled')], default=1, verbose_name='Situação')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='checkout.card', verbose_name='Cartão de crédito')),
                ('credit_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.creditpack', verbose_name='Pacote de crédito')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nome do Gateway')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Gateway de Pagamento',
                'verbose_name_plural': 'Gateways de Pagamento',
            },
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montante'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'money'), (2, 'credit'), (3, 'debit'), (4, 'pix')], unique=True, verbose_name='Método'),
        ),
        migrations.CreateModel(
            name='GatewayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_on_gateway_id', models.CharField(max_length=128, verbose_name='ID de usuário no Gateway')),
                ('receiver_id', models.CharField(max_length=150, null=True, verbose_name='Conta do usuário no Gateway')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.gateway', verbose_name='Gateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário no Gateway',
                'verbose_name_plural': 'Usuários no Gateway',
            },
        ),
        migrations.CreateModel(
            name='GatewayCreditOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_order_on_gateway_id', models.CharField(max_length=150, verbose_name='ID do pedido de crédito no Gateway')),
                ('credit_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.creditorder', verbose_name='Pedido de crédito')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.gateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Pedido no Gateway',
                'verbose_name_plural': 'Pedidos no Gateway',
            },
        ),
        migrations.CreateModel(
            name='GatewayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_on_gateway_id', models.CharField(max_length=150, verbose_name='ID do cartão no Gateway')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_card_set', to='checkout.card', verbose_name='Cartão de Crédito')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.gateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Cartão de Crédito no Gateway',
                'verbose_name_plural': 'Cartões de Crédito no Gateway',
            },
        ),
        migrations.AddField(
            model_name='creditorder',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checkout.paymentmethod', verbose_name='Método de pagamento'),
        ),
        migrations.AddField(
            model_name='creditorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
