# Generated by Django 3.1.5 on 2023-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220124_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagarmeWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagarme_id', models.CharField(max_length=60, verbose_name='Pagarme Webhook ID')),
                ('description', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Pagarme Webhook',
                'verbose_name_plural': 'Pagarme Webhooks',
            },
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'credit'), (2, 'debit'), (3, 'pix')], unique=True, verbose_name='Método'),
        ),
    ]
