# Generated by Django 3.1.5 on 2021-10-12 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'really_bad'), (2, 'bad'), (3, 'regular'), (4, 'good'), (5, 'very_good')], verbose_name='Nota de 1 a 5')),
                ('message', models.CharField(max_length=255, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de entrada')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='review.rating', verbose_name='Avaliação')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
            ],
            options={
                'verbose_name': 'Avaliação de Usuário',
                'verbose_name_plural': 'Avaliações de Usuários',
            },
        ),
        migrations.CreateModel(
            name='PlaceRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.placeads', verbose_name='Lugar')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='review.rating', verbose_name='Avaliação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Avaliação de Lugar',
                'verbose_name_plural': 'Avaliações de Lugares',
            },
        ),
    ]
