# Generated by Django 3.1.5 on 2021-10-12 13:32

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nome de Usuário')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=30, unique=True, verbose_name='WhatsApp')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=60, verbose_name='Sobrenome')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'place_owner'), (2, 'place_customer')], verbose_name='Papel de Usuário')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'blocked')], default=1)),
                ('password', models.CharField(max_length=128, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
    ]
