
BANKS = {1: 'Banco Do Brasil S.A (BB)',
 3: 'Banco Da Amazonia S.A',
 4: 'Banco Do Nordeste Do Brasil S.A.',
 7: 'Bndes (Banco Nacional Do Desenvolvimento Social)',
 10: 'Credicoamo',
 11: 'C.Suisse Hedging - Griffo Cv S.A (Credit Suisse)',
 12: 'Banco Inbursa',
 14: 'Natixis Brasil S.A',
 15: 'Ubs Brasil Cctvm S.A',
 16: 'Ccm Desp Trâns Sc E Rs',
 17: 'Bny Mellon Banco S.A',
 18: 'Banco Tricury S.A',
 21: 'Banco Banestes S.A',
 24: 'Bco Bandepe S.A',
 25: 'Banco Alfa S.A.',
 29: 'Banco Itaú Consignado S.A',
 33: 'Banco Santander Brasil S.A',
 36: 'Banco Bbi S.A',
 37: 'Banco Do Estado Do Pará S.A',
 40: 'Banco Cargill S.A',
 41: 'Banrisul - Banco Do Estado Do Rio Grande Do Sul S.A',
 47: 'Banco Bco Do Estado De Sergipe S.A',
 60: 'Confidence Cc S.A',
 62: 'Hipercard Bm S.A',
 63: 'Banco Bradescard',
 64: 'Goldman Sachs Do Brasil Bm S.A',
 65: 'Banco Andbank S.A',
 66: 'Banco Morgan Stanley S.A',
 69: 'Banco Crefisa S.A',
 70: 'Banco De Brasília (Brb)',
 74: 'Bco. J.Safra S.A',
 75: 'Bco Abn Amro S.A',
 76: 'Banco Kdb Brasil S.A.',
 77: 'Banco Inter S.A',
 78: 'Haitong Bi Do Brasil S.A',
 79: 'Banco Original Do Agronegócio S.A',
 80: 'B&T Cc Ltda',
 81: 'Bbn Banco Brasileiro De Negocios S.A',
 82: 'Banco Topázio S.A',
 83: 'Banco Da China Brasil S.A',
 84: 'Uniprime Norte Do Paraná',
 85: 'Coop Central Ailos',
 89: 'Ccr Reg Mogiana',
 91: 'Unicred Central Rs',
 92: 'Brk S.A',
 93: 'Pólocred Scmepp Ltda',
 94: 'Banco Finaxis',
 95: 'Banco Confidence De Câmbio S.A',
 96: 'Banco B3 S.A',
 97: 'Ccc Noroeste Brasileiro Ltda',
 98: 'CredialianÃ§a Ccr',
 99: 'Uniprime Central Ccc Ltda',
 100: 'Planner Corretora De Valores S.A',
 101: 'Renascenca Dtvm Ltda',
 102: 'Xp Investimentos S.A',
 104: 'Caixa Econômica Federal (Cef)',
 105: 'Lecca Cfi S.A',
 107: 'Banco Bocom Bbm S.A',
 108: 'Portocred S.A',
 111: 'Banco Oliveira Trust Dtvm S.A',
 113: 'Magliano S.A',
 114: 'Central Cooperativa De CrÃ©dito No Estado Do Espírito Santo',
 117: 'Advanced Cc Ltda',
 118: 'Standard Chartered Bi S.A',
 119: 'Banco Western Union',
 120: 'Banco Rodobens S.A',
 121: 'Banco Agibank S.A',
 122: 'Banco Bradesco Berj S.A',
 124: 'Banco Woori Bank Do Brasil S.A',
 125: 'Brasil Plural S.A Banco',
 126: 'Br Partners Bi',
 127: 'Codepe Cvc S.A',
 128: 'Ms Bank S.A Banco De Câmbio',
 129: 'Ubs Brasil Bi S.A',
 130: 'Caruana Scfi',
 131: 'Tullett Prebon Brasil Cvc Ltda',
 132: 'Icbc Do Brasil Bm S.A',
 133: 'Cresol ConfederaÃ§Ã£o',
 134: 'Bgc Liquidez Dtvm Ltda',
 136: 'Unicred Cooperativa',
 137: 'Multimoney Cc Ltda',
 138: 'Get Money Cc Ltda',
 139: 'Intesa Sanpaolo Brasil S.A',
 140: 'Easynvest - Título Cv S.A',
 142: 'Broker Brasil Cc Ltda',
 143: 'Treviso Cc S.A',
 144: 'Bexs Banco De Cambio S.A.',
 145: 'Levycam Ccv Ltda',
 146: 'Guitta Cc Ltda',
 149: 'Facta S.A. Cfi',
 157: 'Icap Do Brasil Ctvm Ltda',
 159: 'Casa Credito S.A',
 163: 'Commerzbank Brasil S.A Banco Múltiplo',
 169: 'Banco OlÃ© Bonsucesso Consignado S.A',
 172: 'Albatross Ccv S.A',
 173: 'Brl Trust Dtvm Sa',
 174: 'Pernambucanas Financ S.A',
 177: 'Guide',
 180: 'Cm Capital Markets Cctvm Ltda',
 182: 'Dacasa Financeira S/A',
 183: 'Socred S.A',
 184: 'Banco Itaú Bba S.A',
 188: 'Ativa S.A Investimentos',
 189: 'Hs Financeira',
 190: 'Servicoop',
 191: 'Nova Futura Ctvm Ltda',
 194: 'Parmetal Dtvm Ltda',
 196: 'Banco Fair Cc S.A',
 197: 'Stone Pagamentos S.A',
 204: 'Banco Bradesco Cartoes S.A',
 208: 'Banco Btg Pactual S.A',
 212: 'Banco Original S.A',
 213: 'Bco Arbi S.A',
 217: 'Banco John Deere S.A',
 218: 'Banco Bs2 S.A',
 222: 'Banco CrÃ©dit Agricole Br S.A',
 224: 'Banco Fibra S.A',
 233: 'Banco Cifra',
 237: 'Next Bank',
 241: 'Banco Classico S.A',
 243: 'Banco Máxima S.A',
 246: 'Banco Abc Brasil S.A',
 249: 'Banco Investcred Unibanco S.A',
 250: 'Banco Bcv',
 253: 'Bexs Cc S.A',
 254: 'Parana Banco S.A',
 260: 'Nu Pagamentos S.A (Nubank)',
 265: 'Banco Fator S.A',
 266: 'Banco Cedula S.A',
 268: 'Barigui Ch',
 269: 'Hsbc Banco De Investimento',
 270: 'Sagitur Cc Ltda',
 271: 'Ib Cctvm Ltda',
 273: 'Ccr De SÃ£o Miguel Do Oeste',
 276: 'Senff S.A',
 278: 'Genial Investimentos Cvm S.A',
 279: 'Ccr De Primavera Do Leste',
 280: 'Avista S.A',
 283: 'Rb Capital Investimentos Dtvm Ltda',
 285: 'Frente Cc Ltda',
 286: 'Ccr De Ouro',
 288: 'Carol Dtvm Ltda',
 290: 'Pagseguro Internet S.A',
 292: 'Bs2 Distribuidora De Títulos E Investimentos',
 293: 'Lastro Rdv Dtvm Ltda',
 298: 'Vips Cc Ltda',
 300: 'Banco La Nacion Argentina',
 301: 'Bpp Instituição De Pagamentos S.A',
 310: 'Vortx Dtvm Ltda',
 318: 'Banco Bmg S.A',
 320: 'Banco Ccb Brasil S.A',
 323: 'Mercado Pago - Conta Do Mercado Livre',
 335: 'Banco Digio S.A',
 336: 'Banco C6 S.A - C6 Bank',
 340: 'Super Pagamentos S/A (Superdital)',
 341: 'Itaú Unibanco S.A',
 348: 'Banco Xp S/A',
 366: 'Banco Societe Generale Brasil',
 370: 'Banco Mizuho S.A',
 376: 'Banco J.P. Morgan S.A',
 389: 'Banco Mercantil Do Brasil S.A',
 394: 'Banco Bradesco Financiamentos S.A',
 399: 'Kirton Bank',
 412: 'Banco Capital S.A',
 422: 'Banco Safra S.A',
 456: 'Banco Mufg Brasil S.A',
 464: 'Banco Sumitomo Mitsui Brasil S.A',
 473: 'Banco Caixa Geral Brasil S.A',
 477: 'Citibank N.A',
 479: 'Banco Itaubank S.A',
 487: 'Deutsche Bank S.A Banco AlemÃ£o',
 488: 'Jpmorgan Chase Bank',
 492: 'Ing Bank N.V',
 494: 'Banco Rep Oriental Uruguay',
 495: 'La Provincia Buenos Aires Banco',
 505: 'Banco Credit Suisse (Brl) S.A',
 545: 'Senso Ccvm S.A',
 600: 'Banco Luso Brasileiro S.A',
 604: 'Banco Industrial Do Brasil S.A',
 610: 'Banco Vr S.A',
 611: 'Banco Paulista',
 612: 'Banco Guanabara S.A',
 613: 'Omni Banco S.A',
 623: 'Banco Pan',
 626: 'Banco Ficsa S.A',
 630: 'Banco Intercap S.A',
 633: 'Banco Rendimento S.A',
 634: 'Banco Triangulo S.A (Banco Triângulo)',
 637: 'Banco Sofisa S.A (Sofisa Direto)',
 641: 'Banco Alvorada S.A',
 643: 'Banco Pine S.A',
 652: 'Itaú Unibanco Holding Bm S.A',
 653: 'Banco Indusval S.A',
 654: 'Banco A.J. Renner S.A',
 655: 'Banco Votorantim S.A',
 707: 'Banco Daycoval S.A',
 712: 'Banco Ourinvest S.A',
 739: 'Banco Cetelem S.A',
 741: 'Banco RibeirÃ£o Preto',
 743: 'Banco Semear S.A',
 745: 'Banco Citibank S.A',
 746: 'Banco Modal S.A',
 747: 'Banco Rabobank Internacional Do Brasil S.A',
 748: 'Sicredi S.A',
 751: 'Scotiabank Brasil',
 752: 'Bnp Paribas Brasil S.A',
 753: 'Novo Banco Continental S.A Bm',
 754: 'Banco Sistema',
 755: 'Bofa Merrill Lynch Bm S.A',
 756: 'Bancoob (Banco Cooperativo Do Brasil)',
 757: 'Banco Keb Hana Do Brasil S.A'}
 
BANK_CHOICES = [
    (1, 'Banco Do Brasil S.A (BB)'),
    (237, 'Bradesco S.A'),
    (104, 'Caixa Econômica Federal (Cef)'),
    (341, 'Itaú Unibanco S.A'),
    (33, 'Banco Santander Brasil S.A'),
    (756, 'Bancoob (Banco Cooperativo Do Brasil)'),
    (260, 'Nu Pagamentos S.A (Nubank)'),
    (77, 'Banco Inter S.A'),
    (4, 'Banco Do Nordeste Do Brasil S.A.'),
    (290, 'Pagseguro Internet S.A'),
    (3, 'Banco Da Amazonia S.A'),
    (7, 'Bndes (Banco Nacional Do Desenvolvimento Social)'),
    (10, 'Credicoamo'),
    (11, 'C.Suisse Hedging - Griffo Cv S.A (Credit Suisse)'),
    (12, 'Banco Inbursa'),
    (14, 'Natixis Brasil S.A'),
    (15, 'Ubs Brasil Cctvm S.A'),
    (16, 'Ccm Desp Trâns Sc E Rs'),
    (17, 'Bny Mellon Banco S.A'),
    (18, 'Banco Tricury S.A'),
    (21, 'Banco Banestes S.A'),
    (24, 'Bco Bandepe S.A'),
    (25, 'Banco Alfa S.A.'),
    (29, 'Banco Itaú Consignado S.A'),
    (36, 'Banco Bbi S.A'),
    (37, 'Banco Do Estado Do Pará S.A'),
    (40, 'Banco Cargill S.A'),
    (41, 'Banrisul - Banco Do Estado Do Rio Grande Do Sul S.A'),
    (47, 'Banco Bco Do Estado De Sergipe S.A'),
    (60, 'Confidence Cc S.A'),
    (62, 'Hipercard Bm S.A'),
    (63, 'Banco Bradescard'),
    (64, 'Goldman Sachs Do Brasil Bm S.A'),
    (65, 'Banco Andbank S.A'),
    (66, 'Banco Morgan Stanley S.A'),
    (69, 'Banco Crefisa S.A'),
    (70, 'Banco De Brasília (Brb)'),
    (74, 'Bco. J.Safra S.A'),
    (75, 'Bco Abn Amro S.A'),
    (76, 'Banco Kdb Brasil S.A.'),
    (78, 'Haitong Bi Do Brasil S.A'),
    (79, 'Banco Original Do Agronegócio S.A'),
    (80, 'B&T Cc Ltda'),
    (81, 'Bbn Banco Brasileiro De Negocios S.A'),
    (82, 'Banco Topázio S.A'),
    (83, 'Banco Da China Brasil S.A'),
    (84, 'Uniprime Norte Do Paraná'),
    (85, 'Coop Central Ailos'),
    (89, 'Ccr Reg Mogiana'),
    (91, 'Unicred Central Rs'),
    (92, 'Brk S.A'),
    (93, 'Pólocred Scmepp Ltda'),
    (94, 'Banco Finaxis'),
    (95, 'Banco Confidence De Câmbio S.A'),
    (96, 'Banco B3 S.A'),
    (97, 'Ccc Noroeste Brasileiro Ltda'),
    (98, 'CredialianÃ§a Ccr'),
    (99, 'Uniprime Central Ccc Ltda'),
    (100, 'Planner Corretora De Valores S.A'),
    (101, 'Renascenca Dtvm Ltda'),
    (102, 'Xp Investimentos S.A'),
    (105, 'Lecca Cfi S.A'),
    (107, 'Banco Bocom Bbm S.A'),
    (108, 'Portocred S.A'),
    (111, 'Banco Oliveira Trust Dtvm S.A'),
    (113, 'Magliano S.A'),
    (114, 'Central Cooperativa De CrÃ©dito No Estado Do Espírito Santo'),
    (117, 'Advanced Cc Ltda'),
    (118, 'Standard Chartered Bi S.A'),
    (119, 'Banco Western Union'),
    (120, 'Banco Rodobens S.A'),
    (121, 'Banco Agibank S.A'),
    (122, 'Banco Bradesco Berj S.A'),
    (124, 'Banco Woori Bank Do Brasil S.A'),
    (125, 'Brasil Plural S.A Banco'),
    (126, 'Br Partners Bi'),
    (127, 'Codepe Cvc S.A'),
    (128, 'Ms Bank S.A Banco De Câmbio'),
    (129, 'Ubs Brasil Bi S.A'),
    (130, 'Caruana Scfi'),
    (131, 'Tullett Prebon Brasil Cvc Ltda'),
    (132, 'Icbc Do Brasil Bm S.A'),
    (133, 'Cresol ConfederaÃ§Ã£o'),
    (134, 'Bgc Liquidez Dtvm Ltda'),
    (136, 'Unicred Cooperativa'),
    (137, 'Multimoney Cc Ltda'),
    (138, 'Get Money Cc Ltda'),
    (139, 'Intesa Sanpaolo Brasil S.A'),
    (140, 'Easynvest - Título Cv S.A'),
    (142, 'Broker Brasil Cc Ltda'),
    (143, 'Treviso Cc S.A'),
    (144, 'Bexs Banco De Cambio S.A.'),
    (145, 'Levycam Ccv Ltda'),
    (146, 'Guitta Cc Ltda'),
    (149, 'Facta S.A. Cfi'),
    (157, 'Icap Do Brasil Ctvm Ltda'),
    (159, 'Casa Credito S.A'),
    (163, 'Commerzbank Brasil S.A Banco Múltiplo'),
    (169, 'Banco OlÃ© Bonsucesso Consignado S.A'),
    (172, 'Albatross Ccv S.A'),
    (173, 'Brl Trust Dtvm Sa'),
    (174, 'Pernambucanas Financ S.A'),
    (177, 'Guide'),
    (180, 'Cm Capital Markets Cctvm Ltda'),
    (182, 'Dacasa Financeira S/A'),
    (183, 'Socred S.A'),
    (184, 'Banco Itaú Bba S.A'),
    (188, 'Ativa S.A Investimentos'),
    (189, 'Hs Financeira'),
    (190, 'Servicoop'),
    (191, 'Nova Futura Ctvm Ltda'),
    (194, 'Parmetal Dtvm Ltda'),
    (196, 'Banco Fair Cc S.A'),
    (197, 'Stone Pagamentos S.A'),
    (204, 'Banco Bradesco Cartoes S.A'),
    (208, 'Banco Btg Pactual S.A'),
    (212, 'Banco Original S.A'),
    (213, 'Bco Arbi S.A'),
    (217, 'Banco John Deere S.A'),
    (218, 'Banco Bs2 S.A'),
    (222, 'Banco CrÃ©dit Agricole Br S.A'),
    (224, 'Banco Fibra S.A'),
    (233, 'Banco Cifra'),
    (237, 'Next Bank'),
    (241, 'Banco Classico S.A'),
    (243, 'Banco Máxima S.A'),
    (246, 'Banco Abc Brasil S.A'),
    (249, 'Banco Investcred Unibanco S.A'),
    (250, 'Banco Bcv'),
    (253, 'Bexs Cc S.A'),
    (254, 'Parana Banco S.A'),
    (265, 'Banco Fator S.A'),
    (266, 'Banco Cedula S.A'),
    (268, 'Barigui Ch'),
    (269, 'Hsbc Banco De Investimento'),
    (270, 'Sagitur Cc Ltda'),
    (271, 'Ib Cctvm Ltda'),
    (273, 'Ccr De SÃ£o Miguel Do Oeste'),
    (276, 'Senff S.A'),
    (278, 'Genial Investimentos Cvm S.A'),
    (279, 'Ccr De Primavera Do Leste'),
    (280, 'Avista S.A'),
    (283, 'Rb Capital Investimentos Dtvm Ltda'),
    (285, 'Frente Cc Ltda'),
    (286, 'Ccr De Ouro'),
    (288, 'Carol Dtvm Ltda'),
    (292, 'Bs2 Distribuidora De Títulos E Investimentos'),
    (293, 'Lastro Rdv Dtvm Ltda'),
    (298, 'Vips Cc Ltda'),
    (300, 'Banco La Nacion Argentina'),
    (301, 'Bpp Instituição De Pagamentos S.A'),
    (310, 'Vortx Dtvm Ltda'),
    (318, 'Banco Bmg S.A'),
    (320, 'Banco Ccb Brasil S.A'),
    (323, 'Mercado Pago - Conta Do Mercado Livre'),
    (335, 'Banco Digio S.A'),
    (336, 'Banco C6 S.A - C6 Bank'),
    (340, 'Super Pagamentos S/A (Superdital)'),
    (348, 'Banco Xp S/A'),
    (366, 'Banco Societe Generale Brasil'),
    (370, 'Banco Mizuho S.A'),
    (376, 'Banco J.P. Morgan S.A'),
    (389, 'Banco Mercantil Do Brasil S.A.'),
    (389, 'Banco Mercantil Do Brasil S.A'),
    (394, 'Banco Bradesco Financiamentos S.A'),
    (399, 'Kirton Bank'),
    (412, 'Banco Capital S.A'),
    (422, 'Banco Safra S.A'),
    (456, 'Banco Mufg Brasil S.A'),
    (464, 'Banco Sumitomo Mitsui Brasil S.A'),
    (473, 'Banco Caixa Geral Brasil S.A'),
    (477, 'Citibank N.A'),
    (479, 'Banco Itaubank S.A'),
    (487, 'Deutsche Bank S.A Banco AlemÃ£o'),
    (488, 'Jpmorgan Chase Bank'),
    (492, 'Ing Bank N.V'),
    (494, 'Banco Rep Oriental Uruguay'),
    (495, 'La Provincia Buenos Aires Banco'),
    (505, 'Banco Credit Suisse (Brl) S.A'),
    (545, 'Senso Ccvm S.A'),
    (600, 'Banco Luso Brasileiro S.A'),
    (604, 'Banco Industrial Do Brasil S.A'),
    (610, 'Banco Vr S.A'),
    (611, 'Banco Paulista'),
    (612, 'Banco Guanabara S.A'),
    (613, 'Omni Banco S.A'),
    (623, 'Banco Pan'),
    (626, 'Banco Ficsa S.A'),
    (630, 'Banco Intercap S.A'),
    (633, 'Banco Rendimento S.A'),
    (634, 'Banco Triangulo S.A (Banco Triângulo)'),
    (637, 'Banco Sofisa S.A (Sofisa Direto)'),
    (641, 'Banco Alvorada S.A'),
    (643, 'Banco Pine S.A'),
    (652, 'Itaú Unibanco Holding Bm S.A'),
    (653, 'Banco Indusval S.A'),
    (654, 'Banco A.J. Renner S.A'),
    (655, 'Neon Pagamentos S.A (Memso Código Do Banco Votorantim)'),
    (655, 'Banco Votorantim S.A'),
    (707, 'Banco Daycoval S.A'),
    (712, 'Banco Ourinvest S.A'),
    (739, 'Banco Cetelem S.A'),
    (741, 'Banco RibeirÃ£o Preto'),
    (743, 'Banco Semear S.A'),
    (745, 'Banco Citibank S.A'),
    (746, 'Banco Modal S.A'),
    (747, 'Banco Rabobank Internacional Do Brasil S.A'),
    (748, 'Sicredi S.A'),
    (751, 'Scotiabank Brasil'),
    (752, 'Bnp Paribas Brasil S.A'),
    (753, 'Novo Banco Continental S.A Bm'),
    (754, 'Banco Sistema'),
    (755, 'Bofa Merrill Lynch Bm S.A'),
    (757, 'Banco Keb Hana Do Brasil S.A'),
]